services:
  api:
    build:
      context: .
      dockerfile: src/EdifactEnergyParser.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MeterDataService__BaseUrl: "http://host.docker.internal:5000"
